### ISSUE TITLE
Icon suggestion

### ISSUE THREAD

**Issue by foursplaysroblox** [GetGet99/Mica-Discord#9]
I found this icon out of no where and I think it should be the icon
![Discord](https://user-images.githubusercontent.com/82078139/215027567-d01b67b6-489a-4cf7-9c56-71d8f6831841.png)

**Comment by GetGet99** [comment]
Unfortunately, I already have an icon made by someone else and I would like to stick to that icon. Thanks for the suggestion, though.

**Comment by foursplaysroblox** [comment]
thanks for commenting in my birthday
